/**
 * some lists for generating random names
 */

'use strict';

module.exports = {
  adjectives: [
    'green',
    'large',
    'professional',
    'random',
    'red',
    'metal',
    'satanic',
    'easy-to-use',
    'dilapidated',
    'janky',
    'expensive',
    'garbage',
    'full-time',
    'green',
    'eco-friendly',
    'gigantic',
    'effulgent',
    'corpulent',
    'didactic',
    'feckless',
    'lachrymose',
    'mordant',
    'munificient',
    'nefarious',
    'puckish',
  ],
  nouns: [
    'sprockets',
    'machines',
    'sacrifices',
    'iterations',
    'warehouses',
    'corpses',
    'tachyons',
    'widgets',
    'grouse',
    'muscles',
    'buckets',
    'dumptsers',
    'materials',
    'components',
    'parts',
    'echoes',
    'humans',
    'centuries',
    'regrets',
    'doubts',
    'counts',
    'cereals',
    'leftovers',
    'scrap',
    'gutters',
  ],
  vendors: [
    'green co',
    'brother and brothers',
    'smithyson',
    'foo and bar',
    'all things imported',
    'extreme extremities',
    'company company',
    'incorporated inc.',
    'example llc',
    'shipping co',
  ],
};
